<? $this->headTitle("My Messages - " . $this->page_title); ?>

<div class="row-fluid">
    <div class="col-xs-12">
        <?= $this->partial('partials/message-filter.phtml'); ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 ">

        <div class="model_submenu">
            <a class="<?= $this->message_action == 'inbox' ? 'active' : '' ?>"
               href="<?= $this->url(array("message_action" => "inbox"), "messages-model") ?>">
                Inbox(<?= $this->unread_count->count; ?>)
            </a>
            <a class="<?= $this->message_action == 'outbox' ? 'active' : '' ?>"
               href="<?= $this->url(array("message_action" => "outbox"), "messages-model") ?>">
                Sent Messages
            </a>
            <a class="<?= $this->message_action == 'archive' ? 'active' : '' ?>"
               href="<?= $this->url(array("message_action" => "archive"), "messages-model") ?>">
                Archive Messages
            </a>
            <a class="<?= $this->message_action == 'compose' ? 'active' : '' ?>"
               href="<?= $this->url(array("message_action" => "compose"), "messages-model") ?>">
                Compose Message
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <?= $this->notice ?>

        <?
        switch ($this->message_action) {

            case "inbox":
            case "archive":
            case "outbox":
                echo $this->partial('partials/message-list.phtml', array("users" => $this->users, "paginator" => $this->paginator, "message_action" => $this->message_action));

                break;

            case "compose":
                echo $this->partial('partials/message-compose.phtml', array("replyto" => $this->replyto));
                break;
        }
        ?>


    </div>

</div>
