<? $this->headTitle('Notification Mail Settings'); ?>
<div class="model_content">
    <? $this->headTitle('Notifications');

    echo $this->partial('partials/model-submenu.phtml',
        array("params" => $this->theme()->view->params,
            "type" => "notifications",
            "acl" => $this->acl
        ));

    echo $this->partial('partials/notification-settings.phtml',
        array(
            //"notifications" => $this->notifications
            "settings" => $this->settings,
            "userSettings" => $this->userSettings
        )
    );
    ?>
</div?