<?php echo $this->partial('application/dashboard/partial/tab-menu'); ?>


<div class="row-fluid">
    <h2>Edit profile</h2>
</div>
<div class="row-fluid">
    <?php
    $this->form
        ->setAttribute
        ('action', $this->url('user-profile/edit-process', array()));
    echo $this->ztbform($this->form);
    ?>
</div>
<script>
    $(document).ready(function () {
        // bind on click event

        $("#myModal").modal('hide');                       // initialized with defaults
        // initialized with defaults

        $("#submit").click(function (e) {
            e.preventDefault();

            // Assign handlers immediately after making the request,
            // and remember the jqXHR object for this request
            var formSerializedArray =
                $('#profile-settings-form').serializeArray();

            objectData = {};

            $.each(formSerializedArray, function () {
                if (this.name == 'submit') {
                    return;
                }

                value = this.value;

                if (objectData[this.name] != null) {
                    if (!objectData[this.name].push) {
                        objectData[this.name] = [objectData[this.name]];
                    }

                    objectData[this.name].push(value);
                } else {
                    objectData[this.name] = value;
                }

            });

            if (typeof objectData.receive_newsletter != 'string')
                objectData.receive_newsletter = '1';

            var settings = {
                dataType: 'json',
                type: 'POST',
                data: objectData,
            };

            var jqxhr =
                $.ajax($('#profile-settings-form').attr('action'), settings)
                    .done(function (response) {
                        //show errors, display notifications
                        formDone(response);
                    })
                    .fail(function () {
                        console.log("error");
                    })
                    .always(function () {
                        // console.log( "complete" );
                    });
        });

        today = new Date();
        $('#birthday').datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: '1900:' + today.getFullYear(),
            dateFormat: "mm/dd/yy",
            maxDate: "-18y"
        })

    })
</script>
