<div class="search_bar visible-xs">
    <form class="form-search form-inline">
        <input type="text" class="form-control input-sm" placeholder="">
    </form>
</div>
<div class="row row-no-margin">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
            <div class="content-block" id="play-block">
                <div class="play-page form-group">
                    <div class="row row-no-margin">
                        <div class="col-sm-12">
                            <div class="panel panel-play">
                                <div class="panel-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#row1">
                                        <h2 class="panel-title">
                                            Board Game
                                            <span class="glyphicon glyphicon-minus pull-right"></span>
                                        </h2>
                                    </a>
                                </div>
                                <div id="row1" class="panel-collapse collapse in ov-auto ">
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Chess</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="<?php
                                                echo $this->url('play', ['action' => 'chess']);
                                                ?>"><img
                                            src="/assets/images/game/chess.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Checkers</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="<?php
                                                echo $this->url('play', ['action' => 'checkers']);
                                                ?>"><img src="/assets/images/game/checker.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="club-img"><img src="/assets/images/banner-ad.jpg" alt="image" height="295"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-no-margin">
                        <div class="col-sm-12">
                            <div class="panel panel-play">
                                <div class="panel-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#row2">
                                        <h2 class="panel-title">
                                             Card Game
                                              <span class="glyphicon glyphicon-minus pull-right"></span>
                                        </h2>
                                    </a>
                                </div>
                                <div id="row2" class="panel-collapse collapse in ov-auto ">
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Spades</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/spades_c.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Poker</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/poker_c.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>ONE</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/uno_c.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Black Jack</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/black-jack_c.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-no-margin">
                        <div class="col-sm-12">
                            <div class="panel panel-play">
                                <div class="panel-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#row3">
                                        <h2 class="panel-title">
                                             Other Game
                                             <span class="glyphicon glyphicon-minus pull-right"></span>
                                        </h2>
                                    </a>
                                </div>
                                <div id="row3" class="panel-collapse collapse in ov-auto ">
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Tic Tac Toe</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="<?php
                                                echo $this->url('play', ['action' => 'tic-tac-toe']);
                                                ?>"><img src="/assets/images/game/tic-tac-toe.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Dominoes</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/dominoes_c.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>4 in a Row</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/4inoneroe_c.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-no-margin">
                        <div class="col-sm-12">
                            <div class="panel panel-play">
                                <div class="panel-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#row4">
                                        <h2 class="panel-title">
                                            Arcade Game
                                            <span class="glyphicon glyphicon-minus pull-right"></span>
                                        </h2>
                                    </a>
                                </div>
                                <div id="row4" class="panel-collapse collapse in ov-auto ">
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Pong</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/pong.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-no-margin">
                        <div class="col-sm-12">
                            <div class="panel panel-play">
                                <div class="panel-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#row5">
                                        <h2 class="panel-title">
                                             Puzzle Game
                                             <span class="glyphicon glyphicon-minus pull-right"></span>
                                        </h2>
                                    </a>
                                </div>
                                <div id="row5" class="panel-collapse collapse in ov-auto ">
                                    <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12  block-box ">
                                        <div class="play-box margin-10">
                                            <div class="play-title">
                                                <h3><strong>Puzzle</strong></h3>
                                            </div>
                                            <div class="play-img"><a href="#"><img src="/assets/images/game/puzzle.jpg" alt="image" class="img-responsive"></a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
