<?php

return array (
  'router' =>
  array (
    'routes' =>
    array (
      'zfcadmin' =>
      array (
        'child_routes' =>
        array (
          'crud' =>
          array (
            'type' => 'Literal',
            'options' =>
            array (
              'route' => '/crud',
              'defaults' =>
              array (
                '__NAMESPACE__' => 'Crud\\Controller',
                'controller' => 'Index',
                'action' => 'list',
              ),
            ),
            'may_terminate' => true,
            'child_routes' =>
            array (
              'default' =>
              array (
                'type' => 'Segment',
                'options' =>
                array (
                  'route' => '/[:controller[/:action]][/:id]',
                  'constraints' =>
                  array (
                    'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                    'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                  ),
                  'defaults' =>
                  array (
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  'controllers' =>
  array (
    'invokables' =>
    array (
      0 => 'Crud\\Controller\\AddressController',
      1 => 'Crud\\Controller\\AlbumsController',
      2 => 'Crud\\Controller\\AnnouncementsController',
      3 => 'Crud\\Controller\\AnsiUomController',
      4 => 'Crud\\Controller\\AutorespondersController',
      5 => 'Crud\\Controller\\AutorespondersTrainController',
      6 => 'Crud\\Controller\\BadWordsController',
      7 => 'Crud\\Controller\\BannersController',
      8 => 'Crud\\Controller\\BlogAccessController',
      9 => 'Crud\\Controller\\BlogCategoriesController',
      10 => 'Crud\\Controller\\BlogPostsController',
      11 => 'Crud\\Controller\\BlogPurchaseController',
      12 => 'Crud\\Controller\\CallLogController',
      13 => 'Crud\\Controller\\CartController',
      14 => 'Crud\\Controller\\CartItemController',
      15 => 'Crud\\Controller\\CatalogAvailabilityController',
      16 => 'Crud\\Controller\\CatalogBuilderProductController',
      17 => 'Crud\\Controller\\CatalogCategoryController',
      18 => 'Crud\\Controller\\CatalogCategoryProductController',
      19 => 'Crud\\Controller\\CatalogCategoryWebsiteController',
      20 => 'Crud\\Controller\\CatalogChoiceController',
      21 => 'Crud\\Controller\\CatalogChoiceOptionController',
      22 => 'Crud\\Controller\\CatalogOptionController',
      23 => 'Crud\\Controller\\CatalogOptionImageController',
      24 => 'Crud\\Controller\\CatalogProductController',
      25 => 'Crud\\Controller\\CatalogProductDocumentController',
      26 => 'Crud\\Controller\\CatalogProductFeatureController',
      27 => 'Crud\\Controller\\CatalogProductImageController',
      28 => 'Crud\\Controller\\CatalogProductOptionController',
      29 => 'Crud\\Controller\\CatalogProductSpecController',
      30 => 'Crud\\Controller\\CatalogProductTypeController',
      31 => 'Crud\\Controller\\CatalogProductUomController',
      32 => 'Crud\\Controller\\CategoriesController',
      33 => 'Crud\\Controller\\ChipsController',
      34 => 'Crud\\Controller\\ChipsPackagesController',
      35 => 'Crud\\Controller\\ConfigController',
      36 => 'Crud\\Controller\\ConfigadminvaluesController',
      37 => 'Crud\\Controller\\ContactController',
      38 => 'Crud\\Controller\\ContactAddressesController',
      39 => 'Crud\\Controller\\ContactCompaniesController',
      40 => 'Crud\\Controller\\ContactCompanyController',
      41 => 'Crud\\Controller\\ContactEmailController',
      42 => 'Crud\\Controller\\ContactPhoneController',
      43 => 'Crud\\Controller\\ContactUrlController',
      44 => 'Crud\\Controller\\CountriesController',
      45 => 'Crud\\Controller\\CountryCityController',
      46 => 'Crud\\Controller\\CountryCodesController',
      47 => 'Crud\\Controller\\CountryProvinceController',
      48 => 'Crud\\Controller\\CustomerController',
      49 => 'Crud\\Controller\\EarningStatsController',
      50 => 'Crud\\Controller\\FeaturedProductController',
      51 => 'Crud\\Controller\\FollowersController',
      52 => 'Crud\\Controller\\FriendsController',
      53 => 'Crud\\Controller\\HiddenModelsController',
      54 => 'Crud\\Controller\\ImagesDeprecatedController',
      55 => 'Crud\\Controller\\InfoController',
      56 => 'Crud\\Controller\\InfoModelinfoController',
      57 => 'Crud\\Controller\\ManagersStudiosController',
      58 => 'Crud\\Controller\\MessagesController',
      59 => 'Crud\\Controller\\MigrationsController',
      60 => 'Crud\\Controller\\ModelController',
      61 => 'Crud\\Controller\\ModelAccessController',
      62 => 'Crud\\Controller\\ModelActionsController',
      63 => 'Crud\\Controller\\ModelBlockAccessController',
      64 => 'Crud\\Controller\\ModelInfoController',
      65 => 'Crud\\Controller\\ModelModeratorController',
      66 => 'Crud\\Controller\\ModelNotesController',
      67 => 'Crud\\Controller\\ModelQuotesController',
      68 => 'Crud\\Controller\\ModelRatesController',
      69 => 'Crud\\Controller\\ModelRatesPendingController',
      70 => 'Crud\\Controller\\ModelRequestsController',
      71 => 'Crud\\Controller\\ModelScheduleController',
      72 => 'Crud\\Controller\\ModelToCategoriesController',
      73 => 'Crud\\Controller\\ModelUserAccessController',
      74 => 'Crud\\Controller\\ModelUserNotesController',
      75 => 'Crud\\Controller\\ModelWallController',
      76 => 'Crud\\Controller\\ModeratorController',
      77 => 'Crud\\Controller\\ModeratorNotesController',
      78 => 'Crud\\Controller\\NewsletterController',
      79 => 'Crud\\Controller\\NewsletterWebsitesController',
      80 => 'Crud\\Controller\\NotificationsController',
      81 => 'Crud\\Controller\\OrderController',
      82 => 'Crud\\Controller\\OrderAddressController',
      83 => 'Crud\\Controller\\OrderFlagLinkerController',
      84 => 'Crud\\Controller\\OrderFlagsController',
      85 => 'Crud\\Controller\\OrderLineController',
      86 => 'Crud\\Controller\\PaymentMethodController',
      87 => 'Crud\\Controller\\PaymentSessionController',
      88 => 'Crud\\Controller\\PaymentsController',
      89 => 'Crud\\Controller\\PaymentsInfoController',
      90 => 'Crud\\Controller\\PermissionsController',
      92 => 'Crud\\Controller\\PledgeController',
      93 => 'Crud\\Controller\\PledgeFunderController',
      94 => 'Crud\\Controller\\PledgePerkController',
      95 => 'Crud\\Controller\\PledgeUpdateController',
      96 => 'Crud\\Controller\\ProductController',
      97 => 'Crud\\Controller\\PurchasedContentController',
      98 => 'Crud\\Controller\\RatesController',
      99 => 'Crud\\Controller\\RatesLimitsController',
      100 => 'Crud\\Controller\\RbCommentsController',
      101 => 'Crud\\Controller\\ReviewsController',
      102 => 'Crud\\Controller\\RulesController',
      103 => 'Crud\\Controller\\ShowsController',
      104 => 'Crud\\Controller\\SoundsController',
      105 => 'Crud\\Controller\\SpecialRequestsController',
      106 => 'Crud\\Controller\\StaticPagesController',
      107 => 'Crud\\Controller\\StudiosController',
      108 => 'Crud\\Controller\\TemplatesController',
      109 => 'Crud\\Controller\\TimezonesController',
      110 => 'Crud\\Controller\\TransferWallController',
      111 => 'Crud\\Controller\\UserController',
      112 => 'Crud\\Controller\\UserAccessController',
      113 => 'Crud\\Controller\\UserAddressesController',
      114 => 'Crud\\Controller\\UserFavoritesController',
      115 => 'Crud\\Controller\\UserNewsletterController',
      116 => 'Crud\\Controller\\UserNotificationsController',
      117 => 'Crud\\Controller\\UserNotificationsMailController',
      118 => 'Crud\\Controller\\UserNotificationsTypeController',
      119 => 'Crud\\Controller\\UserPaidVideosController',
      120 => 'Crud\\Controller\\UserResourceController',
      121 => 'Crud\\Controller\\UserResourceValueController',
      122 => 'Crud\\Controller\\UserRoleController',
      123 => 'Crud\\Controller\\UserRoleLinkerController',
      124 => 'Crud\\Controller\\UserSettingsController',
      125 => 'Crud\\Controller\\UserStudiosController',
      126 => 'Crud\\Controller\\VideoController',
      127 => 'Crud\\Controller\\VideoToCategoriesController',
      128 => 'Crud\\Controller\\WebcamAccessController',
      129 => 'Crud\\Controller\\WebchatHistoryController',
      130 => 'Crud\\Controller\\WebchatLinesController',
      131 => 'Crud\\Controller\\WebchatSessionsController',
      132 => 'Crud\\Controller\\WebchatUsersController',
      133 => 'Crud\\Controller\\WebsiteController',
      134 => 'Crud\\Controller\\ExtLogEntriesController',
      135 => 'Crud\\Controller\\LogoController',
      136 => 'Crud\\Controller\\CountryController',
      137 => 'Crud\\Controller\\PackageController',
      138 => 'Crud\\Controller\\PaymentController',
      139 => 'Crud\\Controller\\PaymentTokenController',
      140 => 'Crud\\Controller\\FundersController',
      141 => 'Crud\\Controller\\InteractionController',
      142 => 'Crud\\Controller\\InteractionsController',
      143 => 'Crud\\Controller\\PhotoController',
      144 => 'Crud\\Controller\\ResourceValuesController',
      145 => 'Crud\\Controller\\ResourcesController',
      146 => 'Crud\\Controller\\ScheduledMediaController',
      147 => 'Crud\\Controller\\MagentoCacheController',
      148 => 'Crud\\Controller\\MagentoCacheTagController',
      149 => 'Crud\\Controller\\MagentoFlagController',
      150 => 'Crud\\Controller\\MagentoSessionController',
      151 => 'Crud\\Controller\\MagentoSetupModuleController',
      152 => 'Crud\\Controller\\UserWarningsController',
    ),
    'abstract_factories' =>
    array (
      0 => 'Crud\\Controller\\CrudControllerFactory',
    ),
  ),
  'view_manager' =>
  array (
    'template_map' =>
    array (
      'crud/default/list' => __DIR__ . '/../view/crud/default/list.phtml',
      'crud/default/create' => __DIR__ . '/../view/crud/default/create.phtml',
      'crud/default/update' => __DIR__ . '/../view/crud/default/update.phtml',
      'crud/default/ajax-list' => __DIR__ . '/../view/crud/default/ajax-list.phtml',
      'partial/form-partial' => __DIR__ . '/../view/partial/form-partial.phtml',
    ),
    'template_path_stack' =>
    array (
      0 => __DIR__ . '/../view',
    ),
  ),
  'service_manager' =>
  array (
    'abstract_factories' =>
    array (
      0 => 'Crud\\Form\\CrudFormFactory',
      1 => 'Crud\\Grid\\CrudGridFactory',
      2 => 'Crud\\Filter\\CrudFilterFactory',
      3 => 'Crud\\View\\CrudViewTemplateFactory',
    ),
  ),
);