<?= $this->partial('solo/dashboard/partial/tab-menu'); ?>

    <?php if ($status === true) : ?>
        <div class="alert alert-success">Password changed successfully.</div>
    <?php elseif ($status === false) : ?>
        <div class="alert alert-error">Unable to update your password. Please try again.</div>
    <?php endif; ?>

    <?php
    $form = $this->changePasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
    $form->setAttribute('method', 'post');

    $form->setAttribute('class', 'form-horizontal center ');
    $form->get('submit')->setOptions(array('skipLabel' => true));
    $form->get('submit')->setAttributes(array("class" => "btn btn-magenta"));

    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());

?>
<div class="row row-no-margin">
    <div class="col-md-4 col-md-offset-4 login forms">
        <h2 class="margin-10 generic-h2 text-center">Change Password for <?php echo $this->zfcUserDisplayName() ?></h2>
    </div>
    <div class="col-md-4 col-md-offset-4 login forms">
        <div class="margin-10 generic-border padding-10">
           <?php  foreach ($form->getElements() as $element) { ?>
               <?php if ($element->getName() == 'identity') { ?>
                   <section>
                       <div class="control-group" id="control-group-passwordVerify">
                           <div class="controls" id="controls-passwordVerify">
                               <input type="hidden" class="form-control" id="<?=$element->getName()?>" placeholder="<?=$element->getLabel()?>">
                           </div>
                       </div>
                       <ul class="help-inline">
                           <li><?php $this->formElementErrors($form->get($element->getName())); ?></li>
                       </ul>
                   </section>
               <?php } elseif ($element->getName() == 'submit') { ?>
                   <section>
                       <div class="control-group" id="control-group-passwordVerify">
                           <button type="submit" name="submit" class="btn btn-info" value="">Save</button>
                       </div>
                   </section>
               <?php } else { ?>
                   <section>
                       <div class="control-group" id="control-group-passwordVerify">
                           <label for="<?=$element->getLabel()?>" class="control-label"><?=$element->getLabel()?></label>
                           <div class="controls" id="controls-passwordVerify">
                               <input type="<?=$element->getName()?>" class="form-control" id="<?=$element->getName()?>" placeholder="<?=$element->getLabel()?>">
                           </div>
                       </div>
                       <ul class="help-inline">
                           <li><?php $this->formElementErrors($form->get($element->getName())); ?></li>
                       </ul>
                   </section>
               <?php } ?>
            <?php  } ?>
        </div>
    </div>
</div>

