
<div class="row-fluid">

    <?php if ($this->showQuickSearch): ?>
        <div class="dataTables_filter pull-right col-sm-6" id="dataTable_filter">
            <label class="pull-right">Search: <input type="text" aria-controls="dataTable"
                                                     class="quick-search form-control"
                                                     value="<?php echo $this->quickSearch ?>">
            </label>
        </div>
    <?php endif; ?>

</div>

<form id="additionalParams" class="form-horizontal">
    <table class="table table-striped">

        <thead>
        <tr>
            <th colspan="2">
                <h3><?=$this->name?></h3>
            </th>
            <th>
                <div class="form-group">
                    <input type="text" name="author" class="form-control" placeholder="Author">
                </div>

            </th>
            <th>
                <div class="form-group">
                    <input type="text" name="contact" class="form-control" placeholder="E-mail">
                </div>
            </th>
            <th colspan="2">
                <div class="form-group pull-left">
                    <select name="visible" class="form-control">
                        <option value="any">Any Status</option>
                        <option value="0">Pending</option>
                        <option value="1">Approved</option>
                    </select>
                </div>
                <div class="form-group pull-right">
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"> </span>
                    </button>
                </div>
            </th>
        </tr>
        <tr>

            <th style="width:90px">Date</th>
            <th>Comment</th>
            <th>Author</th>
            <th>Email</th>
            <th>View</th>
            <th style="width:100px">Action</th>
        </tr>
        </thead>
        <?php foreach ($this->rows as $row) {

            if($row['visible']) {
                $visible = 1;
            } else {
                $visible = 0;
            }
            ?>
            <tr>
                <td>
                    <?php //echo  $row['published']->format('Y-m-d H:m:s'); ?>
                    <?php if(is_string($row['published']))  $row['published'] = new DateTime($row['published']);?>
                    <?php echo formatTime($row['published']->getTimestamp()); ?>
                </td>
                <td>
                    <span class="editable-content" data-mode="inline"

                          data-pk="<?= $row['id']; ?>"
                          data-title="Edit comment"><?php echo $row['content']; ?></span>
                </td>
                <td><?php echo $row['author']; ?></td>
                <td><?php echo $row['contact']; ?></td>
                <td>
                    <?php
                        $icon = 'comment';
                        $tip = 'View thread';
                    if (substr($row['uri'], 1, 5) == 'album') {
                        $icon = 'book';
                        $tip = 'View album';
                    } elseif (substr($row['uri'], 1, 9) == 'guestbook') {
                        $icon = 'eye-open';
                        $tip = 'View guestbook';
                    } elseif (substr($row['uri'], 1, 7) == 'gallery') {
                        $icon = 'picture';
                        $tip = 'View gallery';
                    }elseif (substr($row['uri'], 1, 5) == 'video') {
                        $icon = 'facetime-video';
                        $tip = 'View video';
                    }

                    if($row['domain']){
                        $url = 'http://' . $row['domain'] . $row['uri'];
                    } else {
                        $url = $row['uri'];
                    }
                    ?>

                    <a href="<?php echo $url; ?>" target="_blank">
                        <span class="glyphicon glyphicon-<?=$icon?>" title="<?= $tip ?>" data-toggle="tooltip"
                              data-placement="top"/>
                    </a>

                </td>
                <td>
                    <div class="editable-status" data-value="<?=$visible; ?>" data-pk="<?=$row['id']; ?>" data-title="Change status">
                        <span class="label label-<?=($visible == 0 ? 'warning' : 'success'); ?> pointer"><?= ($visible == 0 ? 'Pending' : 'Visible'); ?></span>
                    </div>
                </td>

            </tr>
        <?php
        }
        ?>
    </table>

</form>
</div>

<div class="row-fluid">
    <div class="col-sm-6 text-left">
        <?php if ($this->showItemPerPage): ?>
            <label class="pull-left">
                <select class="itemPerPage form-control">
                    <?php foreach ($this->itemCountPerPageValues as $item): ?>
                        <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                        <option <?php echo $selected ?>><?php echo $item ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
        <?php endif; ?>
        <?php if($this->showExportToCSV): ?>
            <a href="#" style="margin-left: 10px;" class="export-csv">Export to CSV</a>
        <?php endif;?>
    </div>
    <div class="col-sm-6 text-right">
        <?php if ($this->showPagination): ?>
            <div class="dataTables_paginate paging_bootstrap pagination">
                <?php echo $this->paginator; ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="processing">
    </div>
</div>
<?php echo $this->paramsWrap;?>
</div>
