       <div class="row-fluid">
        <div class="col-sm-6 pull-left">
            <?php if ($this->name): ?>
                <header>
                    <h3><?= $this->name ?></h3>

                </header>
            <?php endif; ?>
        </div>

        <?php if ($this->showQuickSearch): ?>
            <div class="dataTables_filter pull-right col-sm-3" id="dataTable_filter">
                <label class="pull-right">Search: <input type="text" aria-controls="dataTable"
                                                         class="quick-search form-control"
                                                         value="<?php echo $this->quickSearch ?>">
                </label>
            </div>
        <?php endif; ?>

        </div>

        <hr>
        <form id="additionalParams" class="form-horizontal">
    <table class="table table-striped">

        <thead>
        <tr>

            <th class=""></th>
            <th class=""></th>
            <th class=""><input type="text" name="user" class="form-control"
                                     placeholder="Reviewer"></th>
            <th class=""><select name="resourceType" class="form-control">
                    <option value="any">Any type</option>
                    <option value="image">Images</option>
                    <option value="video">Videos</option>
                    <option value="album">Albums</option>

                </select>
            </th>
            <th class="">
                <select name="active" class="form-control">
                    <option value="any">Any Status</option>
                    <option value="0">Pending</option>
                    <option value="1">Approved</option>
                    <option value="-1">Rejected</option>

                </select>


             </th>

            <th class="">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"> </span>
                </button>
            </th>

        </tr> <tr>

            <th class="">Id</th>
            <th class="">Date</th>
            <th class="">Review</th>
            <th class="">Reviewer</th>
            <th class="">Type</th>
            <th class="">Action</th>

        </tr>
        </thead>
        <?php foreach ($this->rows as $row) {

                $status = $row['active'];

                echo '<tr>';
                echo '<td>' . $row['id'] . '</td>';
                echo '<td>' . date('Y-m-d H:i:s', $row['date']) . '</td>';
                echo '<td>' . $row['review'] . '</td>';
                echo '<td>' . ($row['user']->getUsername() ? $row['user']->getUsername() : 'No username') . '</td>';
                echo '<td>' . $row['resourceType'] . '</td>';
                echo '<td><select class="status-0 form-control" data-id="' . $row['id'] . '">'?>
                <option <?php if ($status == 0) echo "selected"; ?> value="0">Pending</option>
                <option <?php if ($status == 1) echo "selected"; ?> value="1">Approved</option>
                <option <?php if ($status == -1) echo "selected"; ?> value="-1">Rejected</option>

                </select></td>
                <?php
                echo '</tr>';

        }
        ?>
    </table>

        </form>
</div>

    <div class="row-fluid">
        <div class="col-sm-6 text-left">
            <?php if ($this->showItemPerPage): ?>
                <label class="pull-left">
                    <select class="itemPerPage form-control">
                        <?php foreach ($this->itemCountPerPageValues as $item): ?>
                            <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                            <option <?php echo $selected ?>><?php echo $item ?></option>
                        <?php endforeach; ?>
                    </select> 
                </label> 
           <?php endif; ?>
           <?php if($this->showExportToCSV): ?>
             <a href="#" style="margin-left: 10px;" class="export-csv">Export to CSV</a>
           <?php endif;?>
        </div>
        <div class="col-sm-6 text-right">
            <?php if ($this->showPagination): ?>
                <div class="dataTables_paginate paging_bootstrap pagination">
                    <?php echo $this->paginator; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="processing">
        </div>
    </div>
    <?php echo $this->paramsWrap;?>
</div>
