<?php
    echo $this->asset('chat_js');
    echo $this->asset('chat_css');
?>

<div id="main-chat-screen">
    <div class="col-md-3">
        <ul id="rooms" class="list-group"></ul>
        <ul id="people" class="list-group"></ul>
    </div>
    <div class="col-md-7">
        <div id="conversation">
            <ul id="msgs" class="list-unstyled"></ul>
        </div>
        <form id="chatForm" class="form-inline">

            <div class="form-group col-md-8">
                <input type="text" class="form-control input-lg" placeholder="Your message" id="msg" style="width:100%">
            </div>

            <input type="submit" name="send" id="send" value="Send" class="btn btn-success btn-lg">

            <input type="button" name="start_button" id="start_button" value="Record" onclick="startButton(event)"
               class="btn btn-info btn-lg">

            <div class="btn-group">
                <button type="button" class="btn btn-lg btn-info dropdown-toggle" data-toggle="dropdown">
                    Actions <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#" name="createRoom" data-toggle="modal" data-target="#roomModal">Create room</a></li>
                    <li><a href="#" name="leave" id="leave">Leave current room</a></li>
                </ul>
            </div>

        </form>
    </div>
    <div class="col-md-2">
        <ul class="list-unstyled" id="updates"></ul>
    </div>
</div>

<!-- Modal start -->
<div class="modal fade" id="roomModal" tabindex="-1" role="dialog" aria-labelledby="createRoomLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="createRoomLabel">Create room</h4>
            </div>
            <div class="modal-body">
                You can create a chat room here. Names have to be unique.
                <form class="form-inline" id="createRoomForm"><input type="text" class="form-control input-lg"
                                                                     placeholder="Room name" id="createRoomName"></form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">Close</button>
                <button data-dismiss="modal" id="createRoomBtn" class="btn btn-success btn-lg">Create room</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal end -->

<script type="text/javascript">
    $(function(){
        socket.emit("joinRoom", 'Lobby');
        $("body > .container").removeClass('container').addClass('container-fluid');
    });
</script>