    <? 
    $disable = "";
    if(isset($_SESSION["rate"]) && isset($_SESSION["rate"]["gallery"])) {
        if(in_array($this->album->id, $_SESSION["rate"]["gallery"])) $disable =  " disableRate";
       
    } ?>


<div class="thumbnail with-caption col-lg-4">
    <a  href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>">
        <img src="<?=$this->album->getCover()?>"> 
    </a> 
    <div class="title">
        <h2><a title="<?=$this->album->name?>" href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>"><?=$this->album->name?> (<?=$this->album->total_photos?>)</a></h2> 
    </div>                 

    <div class="left">
        <div class="stars<?=$disable?>" data-id="<?=$this->album->id?>" data-average="<?=$this->album->rating?>" data-extra="gallery"></div>
    </div>                   
     <div class="right">         
        <?  echo $this->partial('partials/items/like_buttons.phtml', array('id' => $this->album->id, "type" => "gallery")); ?>        
    </div>
    <div class="stats center">
         <a href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>#disqus_thread">Comments</a>
         | 
         <a href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>#reviews"><?=$this->album->total_active_reviews?> reviews</a>
    </div>
    
    
    <?if(Auth::isModel() && $_SESSION['user']['id'] == $this->album->id_model && $this->album->viewable>0){ ?> 
        <p> viewable: <span class="<?=$this->album->viewable<=time()?'red':''?>" ><?=date('m/d/Y',$this->album->viewable)?></span> </p>
    <?}?>
    <?if(Auth::isModel() && $_SESSION['user']['id'] == $this->album->id_model){ ?> 
        <p class="album_controls">
            <a title="edit album" href="<?=$this->url(array("type" => "photo_galeries","id"=>$this->album->id), "model-manage-photos2")?>">edit</a> 
            <a onclick='return confirm("Are you sure you want to delete this album?")' href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name, "action_type"=>"delete"), "model-profile-gallery2")?>" class="right">delete</a>
        </p>
    <?}?>

</div>



  <? /*
<div class="album-box span4">


    <div class="album-box-head">
        <a title="<?=$this->album->name?>" href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>"><?=$this->album->name?> (<?=$this->album->total_photos?>)</a> 
    </div>
    
    <div class="album">
         <div class="album-thumb">
            <a class="a_cover" <?=$this->new_window?'target="_blank"':''?> title="<?=$this->album->name?>" href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>">
                <span class="<?=$this->album->password_required ? 'password_req' : ''?>"></span>
                <img alt="" width="190" height="140" src="<?=$this->album->getCover()?>">
            </a>
            
            <?if(Auth::isModel() && $_SESSION['user']['id'] == $this->album->id_model){ ?> 
            <div class="album_controls">
                <a title="edit album" href="<?=$this->url(array("type" => "photo_galeries","id"=>$this->album->id), "model-manage-photos2")?>">edit</a> 
                <a onclick='return confirm("Are you sure you want to delete this album?")' href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name, "action_type"=>"delete"), "model-profile-gallery2")?>" class="right">delete</a>
            </div>
            <?}?>
            
            <div class="album-stats">
                <a data-disqus-identifier="<?='gallery'.$this->album->id?>" href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>#disqus_thread"></a></div>
            <div class="rating">
                <div class="albumStars<?=$disable?>" data-id="<?=$this->album->id?>" data-average="<?=$this->album->rating?>" data-extra="gallery"></div>
                <b><a href="<?=$this->url(array("id_gallery" => $this->album->id, "name" => $this->album->name), "model-profile-gallery")?>#reviews"><?=$this->album->total_active_reviews?> reviews</a></b> 
             </div>
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="viewable">
    <?if(Auth::isModel() && $_SESSION['user']['id'] == $this->album->id_model && $this->album->viewable>0){ ?> 
        viewable: <span class="<?=$this->album->viewable<=time()?'red':''?>" ><?=date('m/d/Y',$this->album->viewable)?></span>
    <?}else{?>
        &nbsp;
    <?}?>    
    </div>
</div>
*/ ?>