<?php
$this->headTitle()->prepend('Image Preview');
?>

<script src="<?= $this->basePath() ?>/js/jquery.qtip-1.0.0-rc3.min.js"></script>
<link href="<?= $this->basePath() ?>/css/jquery.qtip.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="<?= $this->basePath() ?>/css/zf-table/zf-table.css" media="screen" rel="stylesheet" type="text/css">
<link href="<?= $this->basePath() ?>/js/jquery.countdown.css" media="screen" rel="stylesheet" type="text/css">
<script src="<?= $this->basePath() ?>/js/jquery.dataTables.min.js"></script>
<script src="<?= $this->basePath() ?>/js/zf-table.js"></script>
<script src="<?= $this->basePath() ?>/js/DT_bootstrap_3.js"></script>
<script src="<?= $this->basePath() ?>/js/jquery.pietimer.min.js"></script>
<script src="<?= $this->basePath() ?>/js/jquery.plugin.min.js"></script>
<script src="<?= $this->basePath() ?>/js/jquery.countdown.min.js"></script>

<style>
    #right {

        float: right;

    }

    #timer1 {

        text-align: center;

    }

</style>
<div class="main">

    <div class="container">

        <div class="row">

            <div class="span12">

                <div class="widget stacked">

                    <div class="widget-header">
                        <i class="icon-check"></i>

                        <h3>preview images</h3>
                    </div>

                    <div class="widget-content">
                        <div class="row-fluid">
                            <div class="span2 clearfix" id="right">
                                <center>
                                    <button id="random">Random</button>
                                    <button id="start" class="hidden">Pause</button>
                                    <button id="stop" class="hidden">Stop</button>
                                    <br/> <br/>

                                    <p id="timer" style="height: 50px; text-align: center;"></p>

                                    <p id="timer1"></p></center>
                            </div>
                            <div class="span10 clearfix">
                                <center>
                                    <p class="lead"><?= $this->image->getName(); ?></p>
                                    <a href="<?php echo $this->basePath() . "/uploads/images/" .
                                        $this->image->getId() . '.' . $this->image->getExtension(); ?>"
                                       class="ui-lightbox">
                                        <img
                                            src="<?php echo $this->basePath() . "/uploads/images/" .
                                                $this->image->getId() . '.' . $this->image->getExtension(); ?>"
                                            class="img-polaroid" style="width:70%; height:70%"/>
                                    </a>
                                    <?php   $ratingSet = $this->rating->getRatingSet($this->image->getId());

                                    $average = $ratingSet->getAvarage();?>
                                    <br/><br/>
                                </center>
                                <div class="row-fluid">
                                    <div class="span6 offset7">
                                        <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                                            <a class="a2a_dd" href="http://www.addtoany.com/share_save"></a>
                                            <a class="a2a_button_facebook"></a>
                                            <a class="a2a_button_twitter"></a>
                                            <a class="a2a_button_google_plus"></a>
                                        </div>
                                        <script type="text/javascript"
                                                src="//static.addtoany.com/menu/page.js"></script>
                                        <!-- AddToAny END -->

                                        <br/>

                                        <div class="rating" data-average="<?php
                                        if (!$average) {
                                            echo "0";
                                        } else {
                                            echo $average;
                                        } ?>" data-id="<?= $this->image->getId() ?>"></div>
                                        <div id="saved"></div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row-fluid">
                            <div id="disqus_thread"></div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

<script>
    <?php $route = $this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri()->getPath(); ?>

    $('#random').click(function () {
        var data = {
            random: 1,
            nextUrl: '<?=$this->nextUrl->getSlug()?>'

        };
        $.ajax({
            type: "POST",
            url: '/image/<?=$this->nextUrl->getSlug()?>',
            data: data,
            success: function () {

            },
            error: function (request, textStatus, errorThrown) {

                window.location = request.getResponseHeader('redirectURL');
                return false;

            }

        });

    });

    $('#stop').click(function () {
        var data = {
            random: 0,
            nextUrl: '<?=$this->nextUrl->getSlug()?>'

        };
        $.ajax({
            type: "POST",
            url: '/image/<?=$this->nextUrl->getSlug()?>',
            data: data,
            success: function () {

            },
            error: function (request, textStatus, errorThrown) {

                $("#random").removeClass('hidden');
                $("#start").addClass('hidden');
                $("#stop").addClass('hidden');
                $('#timer').pietimer('pause');
                $('#timer').addClass('hidden');
                $('#timer1').addClass('hidden');
                return false;

            }

        });

    });

    <?php if ($this->random == 1) {?>

    $("#random").addClass('hidden');
    $("#start").removeClass('hidden');
    $("#stop").removeClass('hidden');

    $('#timer').pietimer({
            seconds: 10,
            color: 'rgba(0, 0, 0, 0.8)',
            height: 50,
            width: 50
        },
        function () {
            window.location.href = "/image/<?=$this->nextUrl->getSlug()?>";
        });

    $(document).ready(function () {

        $('#timer').pietimer('start');
        $('#timer1').countdown({until: +10, compact: true, format: 'MM:SS'});

        return false;

    });

    $('#start').click(function () {
        if ($('#start').text() == 'Pause') {
            var pause = $('#start').text();
            $('#timer').pietimer('pause');
            $('#timer1').countdown(pause ? 'pause' : 'pause');
            $('#start').text('Start');
            return false;

        } else {
            var pause = $('#start').text();
            $('#timer1').countdown(pause ? 'resume' : 'resume');

            $('#timer').pietimer('start');

            $('#start').text('Pause');
            return false;

        }

    });

    <?php } else { ?>

    $("#random").removeClass('hidden');
    $("#start").addClass('hidden');
    $("#stop").addClass('hidden');

    <?php } ?>
    <?php $actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";?>

    var disqus_shortname = 'funnyrush'; // required: replace example with your forum shortname
    var disqus_identifier = "<?=$this->image->getId()?>";
    var disqus_title = "<?=$this->image->getSlug()?>";
    var disqus_url = "<?=$actual_link?>";

    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);

    <?php if($_SESSION['user'][$this->image->getId()] == 1) {?>

    $(".rating").jRating({
        bigStarsPath: <?=$this->basePath()?>'/css/icons/stars.png',
        step: true,
        isDisabled: true,
        showRateInfo: false,
        length: 5,
        rateMax: 5,
        onClick: function (element, rate) {

            var data = (rate, 1);

        }
    });
    $('#saved').text('You already voted!');
    <?php } else { ?>

    // get the clicked rate !
    $(".rating").jRating({
        bigStarsPath: <?=$this->basePath()?>'/css/icons/stars.png',
        step: true,
        showRateInfo: false,
        length: 5,
        rateMax: 5,
        onClick: function (element, rate) {

            var data = (rate, 1);

        },
        onSuccess: function () {
            $('#saved').text('Thanks for the vote!');
        }
    });

    <?php } ?>

</script>