<?= $this->partial('application/dashboard/partial/tab-menu'); ?>
<div class="span12">
    <h2>Account information</h2>
</div>
<div class="row-fluid">
    <div class="span12">
        <a href="<?= $this->url("user-account/edit") ?>" class="btn btn-magenta">Edit account</a>
    </div>

</div>
<br/>
<div class="row-fluid">
    <div class="span12">
        <div class="well">
            <dl>

                <?php
                foreach ($this->userSettings as $setting) {
                    if ($setting['entity'] && $setting['value']) {
                        echo '<dt>' . $setting['label'] . '</dt>' . '<dd>' . $this->settingEntities[$setting['key']]->__toString() . '</dd>';
                    } else
                        echo '<dt>' . $setting['label'] . '</dt>' . '<dd>' . $setting['value'] . '</dd>';
                }
                ?>

            </dl>
        </div>
    </div>
</div>
