<script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script>
<script type="text/javascript">
    $(function () {
        tinymce.init({

            selector: "textarea#content",

            relative_urls: false,
            remove_script_host: true,
            document_base_url: "/",
            convert_urls: true,

            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "save table contextmenu directionality emoticons template paste textcolor "
            ],
            external_plugins: {
                "moxiemanager": "/moxiemanager/plugin.min.js"
            },

            // Example content CSS (should be your site CSS)
            //content_css : "/scripts/tiny_mce/themes/advanced/skins/default/content.css",

            // Drop lists for link/image/media/template dialogs
            /*     template_external_list_url : "lists/template_list.js",
             external_link_list_url : "lists/link_list.js",
             external_image_list_url : "lists/image_list.js",
             media_external_list_url : "lists/media_list.js",
             */


            file_browser_callback: ajaxfilemanager //functia pentru upload

        });


        function ajaxfilemanager(field_name, url, type, win) {

            var ajaxfilemanagerurl = "../../../../scripts/tiny_mce/plugins/ajaxfilemanager/ajaxfilemanager.php";
            var view = 'detail';
            switch (type) {
                case "image":
                    view = 'thumbnail';
                    break;
                case "media":
                    break;
                case "flash":
                    break;
                case "file":
                    break;
                default:
                    return false;
            }
            tinyMCE.activeEditor.windowManager.open({
                url: "../../../../scripts/tiny_mce/plugins/ajaxfilemanager/ajaxfilemanager.php?view=" + view,
                width: 782,
                height: 440,
                inline: "yes",
                close_previous: "no"
            }, {
                window: win,
                input: field_name
            });

            /*            return false;
             var fileBrowserWindow = new Array();
             fileBrowserWindow["file"] = ajaxfilemanagerurl;
             fileBrowserWindow["title"] = "Ajax File Manager";
             fileBrowserWindow["width"] = "782";
             fileBrowserWindow["height"] = "440";
             fileBrowserWindow["close_previous"] = "no";
             tinyMCE.openWindow(fileBrowserWindow, {
             window : win,
             input : field_name,
             resizable : "yes",
             inline : "yes",
             editor_id : tinyMCE.getWindowArg("editor_id")
             });

             return false;*/
        }
    });
</script>
