<p>Create your new message with the form below.</p>

<script src="/scripts/jquery.autocomplete.js"></script>
<form action="" method="post" id="messages_compose" class="form form horixontal" rol="form">

        <div class="form-group">
            <label for="sendtouser">Send To</label>

            <div class="form-group_wrapper">
                <?= $this->formText('sendtouser', null) ?>
                <input type="hidden" name="id_receiver" id="id_receiver"
                       value="<?= (isset($this->replyto) ? $this->replyto["id"] : "") ?>"/>
                <input type="hidden" name="receiver_type" id="receiver_type"
                       value="<?= (isset($this->replyto) ? $this->replyto["type"] : "") ?>"/>
            </div>
        </div>


        <div class="form-group">
            <label for="subject">Subject</label>

            <div class="col-xs-12">
                <?= $this->formText('subject', null) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="message">Message</label>

            <div class="col-xs-12">
                <?= $this->formTextarea('message', null, array('cols' => 30, 'rows' => 6)) ?>
            </div>
        </div>
        <div class="form-group">
            <small> *all mail is monitored and personal contact information is forbidden</small>
        </div>


    <div class="form-group text-center">
        <input type="submit" name="send" value="Send Message" class="btn btn-success btn-lg">
        <input type="hidden" name="send" value="Send Message">
    </div>
</form>

<script type="text/javascript">
    var sendTo = document.URL.split('#')[1];

    if (sendTo) {
        $('#sendtouser').val(sendTo);
    }


    $("#sendtouser").tokenInput("/autocomplete/sendtousers", {
        method: "POST",
        tokenLimit: "1",
        resultsLimit: "1",
        hintText: "Type a username",
        onAdd: function (item) {
            $('#id_receiver').val(item.id);
            $('#receiver_type').val(item.type);
        },
        onDelete: function (item) {
            $('#id_receiver').val('');
            $('#receiver_type').val('');
        },
        <? if(isset($this->replyto)) { ?>
        prePopulate: [{id: "<?=$this->replyto["id"]?>", name: "<?=$this->replyto["name"]?>"}]
        <? }  ?>


    });
</script>