<h2 class="page_title">Offers by <?= $this->model->screen_name ?></h2>
<br>
<br>
<br>

<div class="clear"></div>
<h3 class="group_title"><a
        href="<?= $this->url(array("profile_type" => "pledges", "id_model" => $this->model->id, "name" => $this->model->screen_name), "model-profile") ?>">Pledges</a>
</h3>
<div class="clear"></div>

<br><br>

<div class="clear"></div>
<h3 class="group_title">Items for sale</h3>
<div class="clear"></div>

<br><br>

<div class="clear"></div>
<h3 class="group_title">Ongoing auctions</h3>
<div class="clear"></div>

<br><br>

<? /*
<div class="clear"></div>
<h3 class="group_title">Games by <?=$this->model->screen_name?></h3>
<div class="clear"></div>

<br><br>

<div class="clear"></div>
<h3 class="group_title">Fundraiser</h3>
<div class="clear"></div>

<br><br>

<div class="clear"></div>
<h3 class="group_title">Name your price</h3>
<div class="clear"></div>

<br><br>

<div class="clear"></div>
<h3 class="group_title">Items for sale</h3>
<div class="clear"></div>

<br><br>

<div class="clear"></div>
<h3 class="group_title">Ongoing auctions</h3>
<div class="clear"></div>

<br><br>
*/
?>