<?
$values_bt = explode(',', config()->model_body_type);
$body_type = array();
foreach ($values_bt as $v_) {
    $v_ = strtolower(trim($v_));
    $body_type[$v_] = ucwords($v_);
}
$values_ht = explode(',', config()->model_hair_type);
$hair_type = array();
foreach ($values_ht as $v_) {
    $v_ = strtolower(trim($v_));
    $hair_type[$v_] = ucwords($v_);
}
$values_o = explode(',', config()->model_orientation);
$orientation = array();
foreach ($values_o as $v_) {
    $v_ = strtolower(trim($v_));
    $orientation[$v_] = ucwords($v_);
}
?>

<div class="page-content round-corners">
    <h1 class="page-title">More information
        about <?= (Auth::isModel() ? "me" : $this->model->getFirstName() . " " . $this->model->getName()) ?></h1>

    <form action="" method="post">
        <div class="join-box-fields">
            <br>
            <?
            foreach ($this->info_fields as $field) {
                $field_name = ucfirst(str_replace('_', ' ', $field->field));
                echo '<div class="field">';
                echo '<label for="' . $field->id . '">' . $field_name . '</label>';
                echo '<div class="field_wrapper">';
                if ($field->type == "input")
                    echo $this->formText($field->id, $field->value, array('title' => $field_name));
                if ($field->type == "select" || $field->type == "multiselect") {
                    $values_ = explode(',', $field->default_values);
                    $values = array();
                    foreach ($values_ as $v_) {
                        $v_ = strtolower(trim($v_));
                        $values[$v_] = ucwords($v_);
                    }
                }
                if ($field->type == "select")
                    echo $this->formSelect($field->id, $field->value, null, $values);
                if ($field->type == "multiselect")
                    echo $this->formSelect($field->id, explode(",", $field->value), array("multiple" => "multiple"), $values);
                echo '</div>';
                echo '</div>';
            }
            ?>
        </div>

        <br>
        <? if ($this->acl->isAllowed($_SESSION['group'], "model-settings", "edit") || Auth::isModel()) { ?>
            <div class="join-button">
                <input type="submit" name="save2" value="Save" class="btn btn-success">
                <input type="hidden" name="save2" value="Save">
            </div>
        <? } ?>
    </form>
</div>