<div class="page-content round-corners">

    <?= $this->notice ?>
    <h1 class="page-title"><?= $this->moderator->username ?>'s Account Settings</h1>

    <form action="" method="post" id="form_account_settings_admin_moderator">

        <div class="join-box-fields">

            <div class="field">
                <label for="email">Notification email</label>

                <div class="field_wrapper">
                    <?= $this->formText('notification_email', $this->moderator->notification_email, array()) ?>
                </div>
            </div>

        </div>

        <br>
        <? if ($this->acl->isAllowed($_SESSION['group'], "moderator-account-settings", "edit")) { ?>
            <div class="join-button">
                <input type="submit" name="save" value="Save" class="btn btn-success">
                <input type="hidden" name="save" value="Save">
            </div>
        <? } ?>
        <br/>

        <div class="model_notice">
            *This information is for administration use only and will not be shared
        </div>

        <br/>
    </form>

    <input type="hidden" name="moderator_id" value="<?= $this->moderator->id ?>" id="moderator_id">
</div>