<style>
    table .unread {
        font-weight: bold;
    }
</style>
<SCRIPT>
    function check() {
        var ids = '';
        $('.case:checkbox:checked').each(function () {

            if (typeof $(this).val() != 'undefined') {
                ids += $(this).val() + ',';
            }

        });
        $('#multipledelete').val(ids);
    }

    $(function () {

        // add multiple select / deselect functionality
        $("#selectall").click(function () {
            $('.case').attr('checked', this.checked);
            check();
        });

        // if all checkbox are selected, check the selectall checkbox
        // and viceversa
        $(".case").click(function () {

            check();

            // alert(this);
            if ($(".case").length == $(".case:checked").length) {
                $("#selectall").attr("checked", "checked");
            } else {
                $("#selectall").removeAttr("checked");
            }


        });
    });
</SCRIPT>

<div class="page-content round-corners">
    <h1 class="page-title">Notification Mail Settings</h1>

    <br/>

    <? if ($this->settings) {
        ?>
        <form method="POST" action="" name="notification-settings">
            <? foreach ($this->settings as $set) { ?>
                <div class="join-box-fields">
                    <div class="join-box-fields-partial permissions">
                        <div class="field">
                            <label for="<?= $set->type ?>"><?= ucfirst(str_replace("_", " ", $set->type)) ?></label>
                            <? if (in_array($set->type, $this->userSettings)) $check = "checked"; else $check = ""; ?>
                            <input type="checkbox" name="settings[<?= $set->type ?>]" id="<?= $set->type ?>"
                                   class="case" <?= $check ?>/>
                        </div>
                    </div>
                </div>

            <? } ?>
            <div class="join-box-fields">
                <div class="join-box-fields-partial permissions">
                    <div class="field">
                        <label for"selectall">Select all</label>
                        <input type="checkbox" name="settings[all]" class="selectall" id="selectall"/>
                    </div>
                </div>
            </div>
            <div class="join-button">
                <input type="submit" name="save" value="Save" class="btn btn-success" style="clear: both;">
            </div>
        </form>
    <? } ?>


    <div class="clear"></div>

</div>
</div>
</div>