<? if ($this->size) $size = $this->size; else $size = 'small';

if ($this->div) $div = $this->div; else $div = '.stars';

?>
<script type="text/javascript">
    //rating stars
    $(document).ready(function () {
        $("<?=$div?>").each(function () {
            if ($(this).hasClass("disableRate")) {
                disabled = true;
            } else {
                disabled = false;
            }
            $(this).jRating({
                phpPath: '/process',
                action: 'rating',
                isDisabled: disabled,
                bigStarsPath: '/scripts/jrating/icons/stars.png', // path of the icon stars.png
                smallStarsPath: '/scripts/jrating/icons/small.png', // path of the icon small.png
                type: '<?=$size?>', // type of the rate.. can be set to 'small' or 'big'
                length: 5, // nb of stars
                decimalLength: 0, // number of decimal in the rate
                step: true, //fil stats full
                rateMax: 5
            });
        });
    });
</script>