<?php

$modelStatus = $this->user->getState();
//$isFollowing = $this->model->isFollowing();
$isFollowing = 1;
//$rates = $this->model->getModelRates();

if ($modelStatus == 0) {
    $ribbon_css = 'offline';
} elseif ($modelStatus != "0" && strtolower($this->model->quality) == "hd") {
    $ribbon_css = 'high-def';
}
$ribbon_css = 'offline';
?>
<div class="girl-box <?= $ribbon_css ?>">
    <div class="girl-box-head box-bg status_0<?//= $modelStatus?>">
        <? if ($modelStatus != 0) { ?>
            <a href="<? //= $this->url(array("id_model" => $this->user->getId(), "name" => $this->user->getDisplayName()), "watch") ?>"> <?= $modelStatus ?> </a>
        <? } else { ?>
            <span><?= $modelStatus ?></span>
        <? } ?>

    </div>
    <div class="chats <?= $ribbon_css ?>">
        <span
            class="<?//= ($this->model->broadcast_mode) ? (($this->model->broadcast_mode == "duplex" || $this->model->broadcast_mode == "video") ? "" : "no_") : 'no_' ?>webcam"></span>
        <span
            class="<?//= ($this->model->broadcast_mode) ? (($this->model->broadcast_mode == "duplex" || $this->model->broadcast_mode == "audio") ? "" : "no_") : 'no_' ?>microphone"></span>
        <span class="<?//= ($this->model->broadcast_mode) ? "" : 'no_' ?>keyboard"></span>
    </div>
    <div class="girl" id="model_<?= $this->user->getId(); ?>">

        <? if ($this->show_favorite_btn == 1) { ?>
            <a href="javascript:;" onclick="App.user.my_favorites.remove_my_favorites(<?= $this->user->getId() ?>)">
                <img
                    id="favorites_<?= $this->user->getId() ?>" class="remove" src="/images/remove_favorite.png"
                    title="Remove from favorites!" style="margin-top: 0px; margin-bottom: -5px;"></a>
        <? } ?>
        <div class="wrap" style="display: block;">
            <div class="wrap">
                <span class="name" style="float:left;"><?= $this->user->getDisplayNAme() ?></span>
                <span class="details"
                      style="float:right;"><? //= $this->user->getBirthday() ? date('Y', time()) - substr($this->user->getBirthday(), 0, 4) : '' ?>
                    <span class="years">yrs</span></span>
            </div>
            <div class="clear"></div>
            <div class="avatar">
                <div class="avatar-ribbon"></div>
                <img alt="<?= $this->user->getDisplayName(); ?> cover picture" src="<?//= $this->user->getCover() ?>">
            </div>
        </div>
        <div class="clear"></div>
        <div class="girl-info">

            <a class="gray_box"
               href="<? //= $this->url(array("profile_type" => "profile", "id_model" => $this->model->id, "name" => $this->model->screen_name), "model-profile") ?>">View
                My Profile</a>

            <div class="quote"><? //= $this->user->status_profile ?></div>

            <? if ($modelStatus != 0) { ?>
                <div class="location">
                    <div class="wrap">
                        <span class="country"><?//= $this->model->getModelCountry()->name ?></span>
                        <span class="orientation"><?//= $this->model->getModelCategories(1)->name ?></span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="segment">
                    <div class="wrap">
                        <span class="country">Private</span> <span class="number"><?//= $rates['private_chat'] ?></span>
                    </div>
                    <div class="clear"></div>
                    <div class="wrap">
                        <? /*<span class="country">VIP</span> <span class="number"><?=$rates['vip_chat']?></span>*/ ?>
                        <span class="country">Spy</span> <span class="number"><?//= $rates['spy_mode'] ?></span>
                    </div>
                </div>
                <div class="clear" style="display:block; width:auto"></div>
            <? } else { ?>
                <div class="break-line"></div>
                <div class="b_btns">

                    <? if (Auth::isUser()) { ?>
                        <span id="path_follow<?= $this->user->getId() ?>">
                            <? if (!$isFollowing) { ?>
                                <a href="javascript:;" class="button-view-small blue right follow"
                                   onclick="App.user.follow.add(<?= $this->user->getId() ?>)">Follow</a>
                            <? } else { ?>
                                <a href="javascript:;" class="button-view-small blue right follow"
                                   onclick="App.user.follow.remove(<?= $this->user->getId() ?>)">Unfollow</a>
                            <? } ?>


                            <ul class="follow_options">
                                <li>
                                    <? if ($isFollowing->new_photo > 0) { ?>
                                        <input onclick="App.user.follow.remove(<?= $this->user->getId() ?>, 'photo')"
                                               type="checkbox" name="photo" id="photo<?= $this->user->getId() ?>"
                                               data-id="<?= $this->model->id ?>" value="New photo"/>
                                    <? } else { ?>
                                        <input onclick="App.user.follow.add(<?= $this->user->getId() ?>, 'photo')"
                                               type="checkbox" name="photo" id="photo<?= $this->user->getId() ?>"
                                               data-id="<?= $this->user->getId() ?>" value="New photo"/>
                                    <? } ?>
                                    <label for="photo<?= $this->user->getId() ?>">New photos</label>
                                </li>
                                <li>
                                    <? if ($isFollowing->new_video > 0) { ?>
                                        <input onclick="App.user.follow.remove(<?= $this->user->getId() ?>, 'video')"
                                               type="checkbox" name="video" checked="checked"
                                               id="video<?= $this->user->getId() ?>" data-id="<?= $this->user->getId() ?>"
                                               value="New video"/>
                                    <? } else { ?>
                                        <input onclick="App.user.follow.add(<?= $this->user->getId() ?>, 'video')"
                                               type="checkbox" name="video" id="video<?= $this->user->getId() ?>"
                                               data-id="<?= $this->user->getId() ?>" value="New video"/>
                                    <? } ?>
                                    <label for="video<?= $this->user->getId() ?>">New videos</label>
                                </li>
                            </ul>

                        </span>
                    <? } else { ?>
                        <a class="button-view-small blue right" href="/login/">Follow</a>
                    <? } ?>
                    <? if (Auth::isUser()) { ?>
                        <a class="button-view-small blue left"
                           href="<?= $this->url(array("message_action" => "compose"), "messages") ?>#<?= $this->user->getDisplayName() ?>">Send
                            Message</a>
                    <? } else { ?>
                        <a class="button-view-small blue left" href="/login/">Send Message</a>
                    <? } ?>
                    <div class="clear"></div>
                </div>
            <? } ?>
        </div>
    </div>

    <div class="girl-box-bottom box-bg status_<?= $modelStatus ?>">
        <? if ($modelStatus['id_status'] != 0) { ?>
            <a href="<?//= $this->url(array("id_model" => $this->model->id, "name" => $this->model->screen_name), "watch") ?>">Watch
                Me Now</a>
        <? } else { ?>
            <a href="<?//= $this->url(array("profile_type" => "profile", "id_model" => $this->model->id, "name" => $this->model->screen_name), "model-profile") ?>">Offline</a>
        <? } ?>
    </div>
    <div class="shadow"></div>
</div>