<?php
if (isset($this->formId))
    $this->form->setAttribute("id", $this->formId);

echo $this->ztbForm($this->form);
?>

<script type="text/javascript">

    $('<?=($this->formId ? '#' . $this->formId.' ' : '')?>input[name="submit"]').on("click", function (e) {
        saveForm();
        e.preventDefault();
    });

    function saveForm() {
        postData = $("form<?=($this->formId ? '#' . $this->formId : '')?>").serializeArray();

        // Assign handlers immediately after making the request,
        // and remember the jqXHR object for this request
        var jqxhr = $.ajax({
            url: "<?php echo $this->ajaxAction?>",
            type: "POST",
            data: postData,
            beforeSend: function (xhr) {
                //xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
                if ($("form .alert-holder").length > 0) {
                    $("form .alert-holder").html();
                } else {
                    $("form").prepend('<div class="alert-holder"></div');
                    $("form .alert-holder").prepend('<div class="alert-holder"></div>');
                }
                $('.control-group').removeClass("error");
                $("form .alert-holder").html('<div class="alert alert-info">Saving...</div>');

            },
            success: function (data, textStatus, jqXHR) {
                //data: return data from server
                //console.log(data.message);
                $("form .alert-holder").html(data.message);
                if (data.status == 'fail') {
                    $.each(data.errors, function (key, element) {
                        //$('[name="' + key + '"]').parents().eq(1).addClass("error");
                        $('#control-group-' + key).addClass("error");
                    });
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                //if fails
            }
        })
            .done(function () {
                // $("form .alert-holder").html('<div class="alert alert-success">Done</div');
            })
            .fail(function () {
            })
            .always(function () {
                $(".alert button.close").click(function () {
                    $(this).parent().remove();
                });
            });

        // Perform other work here ...

        // Set another completion function for the request above
        jqxhr.always(function () {
            //alert( "second complete" );
        });
    }
</script>                                            