<?
$title = "Add newsletter";
$this->headTitle($title); ?>
<div class="page-content round-corners">
    <div class="moderator_submenu">
        <a class="selected" href="/admin/newsletter-add">Add Newsletter</a>
        <a class="" href="/admin/newsletter-list">Newsletter List</a>
    </div>

</div>
<div class="page-content round-corners">

    <?= $this->notice ?>
    <h1 class="page-title"><?= $title ?></h1>

    <form action="" method="post" id="">
        <div class="join-box-fields">

            <div class="field">
                <label for="publish_date">Title</label>

                <div class="field_wrapper">
                    <?= $this->formText('title', "", array("class" => "")) ?>
                </div>
            </div>

            <div class="field">
                <label for="content">Content</label>

                <div class="field_wrapper">
                    <?= $this->formTextarea('content', $this->ann->text, array('cols' => 30, 'rows' => 20, 'class' => 'content')) ?>
                </div>
            </div>

            <div class="field">
                <label for="publish_date">Publish</label>

                <div class="field_wrapper">
                    <?= $this->formText('publish_date', date('m/d/Y', time()), array("class" => "small_tfield_date")) ?>
                </div>
            </div>

            <div class="field">
                <label for="id_website">Site</label>

                <div class="field_wrapper">
                    <?= $this->formSelect('id_website', '0', array("multiple" => "multiple"), $this->websites) ?>
                </div>
            </div>

            <div class="field">
                <label for="select_all_website">All websites</label>

                <div class="field_wrapper">
                    <?= $this->formCheckbox('select_all_website') ?>
                </div>
            </div>

        </div>

        <br>

        <div class="join-button">
            <input type="submit" name="save" value="Save" class="btn btn-success">
        </div>
    </form>


</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#select_all_website').on('click', function(){
            el = $(this);
            $.each($('#id_website option'), function (){
                $(this).prop('selected', el.prop("checked"));
            })
        })
    })
</script>


<link type="text/css" rel="stylesheet" media="screen" href="/themes/default/css/jquery-ui/jquery-ui-1.8.20.custom.css">
<script src="/scripts/jquery.ui.datepicker.js"></script>
<script type="text/javascript">
    $(function () {
        $("#publish_date").datepicker({});
    });
</script>
<?=$this->partial('partials/editor.phtml')?>