<?
switch ($this->params['manage']) {
    case 'add':
        $this->headTitle('Add ' . ucwords($this->params['type']) . ' Rule');
        break;

    case 'edit':
        $this->headTitle('Edit ' . ucwords($this->params['type']) . ' Rule');
        break;

    default:
        $this->headTitle(ucwords($this->params['type']) . ' Rules');
        break;
}

$user = Zend_Registry::get('service_manager')->get('zfcuser_auth_service')->getIdentity();

?>

<div class="page-content round-corners">

    <?= $this->notice ?>
    <? if (!$this->params['manage']) { ?>

        <h1 class="page-title"><?= ucwords($this->params['type']) ?> Rules</h1>

        <div class="row">
            <div class="col-md-4">
                RULE
            </div>
            <div class="col-md-1">
                FREE CHAT
            </div>
            <div class="col-md-1">
                PAID CHATS
            </div>
            <div class="col-md-1">
                Videos
            </div>
            <div class="col-md-1">
                Photos
            </div>
            <div class="col-md-1">
                Fine
            </div>
            <div class="col-md-3">
                Additional penalties
            </div>
        </div>

       <?php
        if (count($this->rules) > 0) {
            foreach ($this->rules as $rule) {
            $cycle = $this->cycle(array("light", "dark"))->next();
            echo '<div class="row">
                <div class="col-md-4">' . $rule->title . '</div>
                <div class="col-md-1" ' . (trim(strtolower($rule->free_chat)) == 'yes' ? 'class="yes"' : (trim(strtolower($rule->free_chat)) == 'no' ? 'class="no"' : '')) . '>' . $rule->free_chat . '</div>
                <div class="col-md-1" ' . (trim(strtolower($rule->paid_chat)) == 'yes' ? 'class="yes"' : (trim(strtolower($rule->paid_chat)) == 'no' ? 'class="no"' : '')) . '>' . $rule->paid_chat . '</div>
                <div class="col-md-1" ' . (trim(strtolower($rule->videos)) == 'yes' ? 'class="yes"' : (trim(strtolower($rule->videos)) == 'no' ? 'class="no"' : '')) . '>' . $rule->videos . '</div>
                <div class="col-md-1" ' . (trim(strtolower($rule->photos)) == 'yes' ? 'class="yes"' : (trim(strtolower($rule->photos)) == 'no' ? 'class="no"' : '')) . '>' . $rule->photos . '</div>
                <div class="col-md-1" >' . ($rule->fine ? '$'.$rule->fine : '') . '</div>
                <div class="col-md-3" ' . (trim(strtolower($rule->fine_text)) ? 'class="penalties"' : '') . '>' . $rule->fine_text . '</div></div>';
            }
        } else {
            echo '<div class="row"><div class="col-md-12">*No rules found.</div></div>';
        }
        ?>
        <div class="row>">
            <div class="col-md-12">
                <br/>
                *&nbsp;&nbsp; after administration decision<br>
                **&nbsp; by user request only<br>
                *** by model request only<br>
                <br/>
                [ if you are other kind of user, please login into your account and check the rules again as they may be
                different from the ones visible here ]
            </div>
        </div>
    <? } ?>
</div>

