<?
$page_title = "Photo Watermark and Video Logo";

$this->headTitle($page_title);
?>

<div class="page-content round-corners">
    <h1 class="page-title"><?= $page_title ?></h1>

    <?= $this->notice ?>

    <form action="" method="post" enctype="multipart/form-data">
        <div class="join-box-fields">
            <div class="field">
                <label for="watermark">Upload Watermark</label>

                <div class="field_wrapper">
                    <?= $this->formFile('watermark', array()) ?>
                </div>
                <div class="field_wrapper">

                    <a class="a_cover" rel="group" href="/uploads/watermarks/watermark.png">
                        <img alt="Logo player" title="logo player" height="50" src="/uploads/watermarks/watermark.png">
                    </a>
                </div>

            </div>
            <div class="field">
                <label for="videologo">Upload Video Logo</label>

                <div class="field_wrapper">
                    <?= $this->formFile('videologo', array()) ?>
                </div>
                <div class="field_wrapper">

                    <a class="a_cover" rel="group" href="/uploads/watermarks/logo-player.png">
                        <img alt="Logo player" title="logo player" height="50" src="/uploads/watermarks/logo-player.png">
                    </a>
                </div>
            </div>
            <div class="join-button">
                <input type="submit" name="save" value="Save" class="btn btn-success">
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $("a[rel=group]").fancybox({
            'transitionIn': 'none',
            'transitionOut': 'none',
            'titlePosition': 'outside'
        });
    });
</script>