<?
$title = 'Blog posts';
$this->headTitle($title);

$filters = array(
    "" => "all posts",
    "public" => "public posts",
    "member" => "member posts",
    "performer" => "performer posts",

);

echo $this->partial('partials/moderator-submenu.phtml',
    array("params" => $this->theme()->view->params,
        "type" => "model",
        "acl" => $this->acl,
        "user" => $this->model));

?>

<div class="page-content round-corners">
    <h1 class="page-title"><?= $title ?></h1>
    <? if ($this->paginator) { ?>
        <? foreach ($this->paginator as $this->article) { ?>
            <? echo $this->partial("blog/blog-list-item-small.phtml", $this); ?>
        <? } ?>
    <? } ?>
    <div class="clear"></div>
</div>     

