<?php $page_title = "Manage blog"; ?>
<div class="model_content">
    <? echo $this->partial("partials/model-submenu.phtml", array("type" => "blog-controller", $this)); ?>
    <div class="page-content round-corners">
        <?= $this->notice ?>

        <h1 class="page-title"><?= $page_title ?></h1>

        <? if ($this->paginator) { ?>
            <? foreach ($this->paginator as $this->article) { ?>
                <? echo $this->partial("blog/blog-list-item-small.phtml", $this); ?>
            <? } ?>
        <? } ?>

        <div class="clear"></div>

        <? echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>

    </div>
</div>