<?
$page_title = "New blog post";

$this->headTitle($page_title);

$this->createdby = array("model_" . user()->id => user()->screen_name);
if ($this->moderator)
    $this->createdby["moderator_" . $this->moderator->id_moderator] = ($this->moderator->screen_name ? $this->moderator->screen_name : $this->moderator->username);

$accessArr = array();

if ($this->access) {
    foreach ($this->access as $access) {
        if ($access["date"] > 0)
            $accessArr[$access["type"]]["date"] = date("d/m/Y H:i", $access["date"]);
        else
            $accessArr[$access["type"]]["date"] = "";

        $accessArr[$access["type"]]["chips"] = $access["chips"];
    }
}
$this->accessArr = $accessArr;
//p($this->article->toArray(),1 );
//p(array_key_exists("vip",$accessArr),1);
?>


<div class="model_content">
    <? echo $this->partial("partials/model-submenu.phtml", array("type" => "blog-controller", $this)); ?>
    <?= $this->notice ?>
    <div class="page-content round-corners">


        <h1 class="page-title"><?= $page_title ?></h1>
        <? echo $this->partial("blog/post-add-form.phtml", $this); ?>
        <br/>

    </div>
</div>        
