<div class="model_content">
    <?
    $page_title = "Add perks";

    $this->headTitle($page_title);


    ?>


    <? echo $this->partial("partials/model-submenu.phtml", array("type" => "pledges", "params" => $this->params)); ?>
    <?= $this->notice ?>
    <div class="page-content round-corners">
        <h1 class="page-title"><?= $page_title ?></h1>
        <?php echo $this->partial("pledge/perk-add-form.phtml", $this); ?>

    </div>
    <?php echo $this->partial("pledge/perk-list.phtml", $this); ?>
</div>
 