<?
$page_title = "Add/edit pledge";

$this->headTitle($page_title);


?>
<?php $timestamp = time(); ?>




<div class="model_content">
    <? echo $this->partial("partials/model-submenu.phtml", array("type" => "pledges", "params" => $this->params)); ?>
    <div class="page-content round-corners">
        <?= $this->notice ?>

        <h1 class="page-title"><?= $page_title ?></h1>
        <?php echo $this->partial("pledge/pledge-add-form.phtml", $this); ?>

        <br/>

    </div>
</div>   