<?
$page_title = "Pledges ";

$this->headTitle($page_title);


?>
<div class="model_content">
    <? echo $this->partial("partials/model-submenu.phtml", array("type" => "pledges", "params" => $this->params)); ?>
    <?= $this->notice ?>
    <div class="page-content round-corners">


        <h1 class="page-title"><?= $page_title ?></h1>

        <br/>
        <? echo $this->partial("pledge/pledge-list.phtml", $this); ?>
    </div>
</div>        
    
