<? $this->headTitle('Pledges'); ?>
<div class="col-xs-12">
    <div class="row">
        <? //echo $this->partial('pledge/filter-menu.phtml', $this); ?>
    </div>
    <div class="row">
        <div class="content">
            <div class="title-pledge">
                <h2>Staff chosen</h2>
            </div>
            <div class="row">
                <div class="tab-content col-md-10">
                    <div class="tab-pane" id="tab_a">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/pledge/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">3d</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> 3D</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class=""project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab_b">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/pledge/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Art</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Art</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab_c">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/pledge/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Comics</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Comics</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab_d">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/pledge/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Design</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Design</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab_e">
                        <div class="row">
                            <div class="col-sm-4">
                                <img src="images/pledge/photo-original.png" class="img-responsive">
                            </div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Film</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Film</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab_f">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/pledge/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Fashion</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Fashion</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="tab_g">
                        <div class="row">
                            <div class="col-sm-4"><img src="images/pledge/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Music</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Music</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane active" id="tab_h">
                        <div class="row">
                            <div class="col-sm-4"><img src="/assets/images/photo-original.png" class="img-responsive"></div>
                            <div class="col-sm-8">
                                <h3 class="no-margin">Photography</h3>
                                <div class="form-group text-muted"><small>by Anakhaliya</small></div>
                                <p class="form-group">A multi-media, immersive contemporary dance work that explores artistic ownership through street art. May 15-17, RIFT Blackbox Theater. </p>
                                <div>
                                    <p><a href="#" class="text-muted"><i class="fa fa-tag"></i> Photography</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="text-muted"><i class="fa fa-map-marker"></i> Miami, FL </a></p>
                                </div>
                                <div class="NS_project__baseball_card_stats">
                                    <div class="project-pledged-wrap bg-grey mb1 clip">
                                        <div class="project-pledged bg-th full-height" style="width: 69.73%"></div>
                                    </div>
                                    <ul class="project-stats no-margin ">
                                        <li class=""> <strong class="block h4">69%</strong> <span class="text-muted">Funded</span> </li>
                                        <li class=""> <strong class="block h4"><span class="money usd no-code">$2,092</span></strong> <span class="text-muted">Pledged</span> </li>
                                        <li class=""> <strong class="block h4">44</strong> <span class="text-muted">Backers</span> </li>
                                        <li class=""> <strong class="block h6">
                                                <div class="num h4">10</div>
                                            </strong>
                                            <div class="span text text-muted" data-word="left">Days to go</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="nav  nav-stacked col-md-2 nav-verticle">
                    <li class=""><a href="#tab_a" data-toggle="pill">3d</a></li>
                    <li class=""><a href="#tab_b" data-toggle="pill">Art</a></li>
                    <li class=""><a href="#tab_c" data-toggle="pill">Comics</a></li>
                    <li class=""><a href="#tab_d" data-toggle="pill">Design</a></li>
                    <li class=""><a href="#tab_e" data-toggle="pill">Film</a></li>
                    <li class=""><a href="#tab_f" data-toggle="pill">Fashion</a></li>
                    <li><a href="#tab_g" data-toggle="pill">Music</a></li>
                    <li class="active"><a href="#tab_h" data-toggle="pill">Photography</a></li>
                </ul>
                <!-- tab content -->
            </div>
        </div>

        <div class="title-pledge">
            <h2>Bounties</h2>
        </div>

        <div class="col-lg-4 col-sm-6 col-md-4 col-xs-12 ">
            <div class="col-sm-1s2 pledge-box">
                <div class="boxxmain">
                    <img src="/assets/images/banner-ad.jpg" height="300" width="360">
                </div>
            </div>
        </div>

        <? if (count($this->paginator)) {
            foreach ($this->paginator as $this->pledge) {
                echo $this->partial("pledge/pledge-list-item.phtml", $this);
            }

        } else {
            echo "No pledge found!";
        }
        ?>

        <div class="clearix"></div>
    </div>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');  ?>
</div>

<link rel="stylesheet" href="/scripts/countdown/jquery.countdown.css">
<script type="text/javascript" src="/scripts/countdown/jquery.countdown.js"></script>

<script>
    $(document).ready(function () {
        <? if(Auth::isLogged()) { ?>
        var logged = true;
        <? } else { ?>
        var logged = false;
        <? } ?>
        $(".pledge").each(function () {
            $(this).mouseleave(function () {
                element = $(this);
                setTimeout(function () {
                    element.children(".buttons").children(".pledge_form").html('');
                }, 3000);
            });
        });
        var login = '<p class="shadow"><a class="btn btn-sm btn-primary" href="/login">Login</a></p>';
        $(".pledge_like").click(function (e) {
            e.preventDefault();
            if (!logged) {
                $(this).parent().children(".pledge_form").html(login);
            } else {
                if ($(this).hasClass("liked")) return;
                if ($(this).data("action") == 'likes')
                    option_value = 1;
                else
                    option_value = 0;

                var this_elem = $(this);
                var request = $.ajax({
                    url: "/process",
                    type: "POST",
                    data: {
                        action: "likes",
                        item: $(this).data("id"),
                        item_type: "pledge",
                        option: option_value
                    },
                    dataType: "html"
                });

                request.done(function (msgs) {
                    msg = $.parseJSON(msgs);
                    if (msg.like_status == 'ok') {
                        this_elem.data("action", "dislikes");
                        this_elem.text("liked");
                        this_elem.addClass("liked");
                        this_elem.click(function (ev) {
                            ev.preventDefault();
                            return;
                        });
                        this_elem.parent().children(".pledge_form").html('<p class="shadow">Thanks</p>');
                    } else if (msg.like_status == 'is_voted') {
                        this_elem.data("action", "dislikes");
                        this_elem.text("liked");
                        this_elem.addClass("liked");this_elem.parent().children(".pledge_form").html('<p class="shadow">You allready like this!</p>');
                        ;
                    }
                });

                request.fail(function (jqXHR, textStatus) {
                    this_elem.parent().children(".pledge_form").html('<p class="shadow">Fail! Try later!</p>');
                    ;
                });
            }

        });

        //open pledge page on pledge list item click
        $(".pledge_holder").on("click", function () {
            window.location = $(this).children(".title").children("a").attr("href");
        });

    });

    $(function () {
        $(".progressbar").each(function () {
            $(this).progressbar({
                value: $(this).data("percent")
            })
        });

        $('.countdown').each(function () {

            var startCounter = new Date($(this).data("time"));

            $(this).countdown({
                until: startCounter,
                compact: true,
                layout: '{dn}{sep}{hnn}{sep}{mnn}{sep}{snn} ',
                description: ''
            });
        });

        $('.countdowndays').each(function () {

            var startCounter = new Date($(this).data("time"));

            $(this).countdown({
                until: startCounter,
                compact: true,
                layout: '{dn} ',
                description: ''
            });
        });
    });
</script>

