<?
$start_y = 2012;
$end_y = date("Y");

if ($end_y > $start_y)
    $period = $start_y . " - " . $end_y;
else
    $period = $start_y;

?>
<div class="row footer">
    <p class="center">
        <a href="/page/u_s_c_section_2257">18 U.S.C. & 2257 Record-Keeping Requirements Compliance Statement</a> |
        <a href="/page/technical_support/">Support</a> |
        <a href="/page/faq/">FAQ</a> |
        <a href="/contact">Contact</a>

        <br>
        Content Copyright <?= $period ?> <a href="http://anakaliyah.com">Anakaliyah.com</a> &copy; All right reserved


    </p>
</div>
</div> <!--content -->