<link type="text/css" rel="stylesheet" media="screen" href="/themes/default/css/jquery-ui/jquery-ui-1.8.20.custom.css">
<script src="/scripts/jquery.ui.datepicker.js"></script>
<script type="text/javascript">
    $(function() {
        $( "#want_date" ).datepicker({ 
                minDate: 0, 
                maxDate: "+3M"
            });
    });
</script>
<?
    $minutes = array(''=>'min');
    for($i=0;$i<60;$i++) $minutes[$i] = $i;
    
    $seconds = array(''=>'sec');
    for($i=0;$i<60;$i++) $seconds[$i] = $i;
   
?>
<div class="row">
    <?=$this->notice?>
    <h2 class="title">Make a special request for <?=$this->model->screen_name?></h2>
</div>
<div class="row">
    <form action="" method="post" class="form-horizontal" id="form_special_request">
    
<?  echo form_field(array("type" => "select", "name" => "item", "value" => $_SESSION['form_special_request']['item'], "label" => "Type"), $attr = array("class" => "col-lg-12"), $options = $this->special_items, $icon = ""); ?>
      
        <div class="join-box-fields">

            <div class="field">
            <label for="item">Type</label> 
                <div class="field_wrapper">
                    <?=$this->formSelect('item', $_SESSION['form_special_request']['item'], null, $this->special_items) ?>
                </div>
            </div> 
            
            <div class="field">
            <label for="duration">Duration</label> 
                <div class="field_wrapper">
                    <?=$this->formSelect('duration_h', $_SESSION['form_special_request']['duration_h'], null, array(""=>"hour", "0"=>"0", "1"=>"1", "2"=>"2", "3"=>"3")) ?> : 
                    <?=$this->formSelect('duration_m', $_SESSION['form_special_request']['duration_m'], null, $minutes) ?> :
                    <?=$this->formSelect('duration_s', $_SESSION['form_special_request']['duration_s'], null, $seconds) ?> :
                    <span class="field_notice">*Video only (min 60 sec, max 3 hour) </span>
                </div>
            </div> 
                        
            <div class="field">
                <label for="offer">Offer</label>
                <div class="field_wrapper">
                    <?=$this->formText('offer', $_SESSION['form_special_request']['offer'], array("class"=>"small_tfield"))?>
                    <span class="field_notice">*How much are you willing to pay</span>
                </div>
            </div>
            
            <div class="field">
                <label for="deposit">Deposit</label>
                <div class="field_wrapper">
                    <?=$this->formText('deposit', $_SESSION['form_special_request']['deposit'], array("class"=>"small_tfield"))?>
                    <span class="field_notice">*Must have to be taken seriously</span>
                    
                </div>
            </div>                
            
            <div class="field">
                <label for="description">Description</label>
                <div class="field_wrapper">
                    <?=$this->formTextarea('description', $_SESSION['form_special_request']['description'], array('cols'=>30,'rows'=>3))?>
                </div>
            </div>
            
            <div class="field">
                <label for="terms">Terms</label>
                <div class="field_wrapper">
                    <?=$this->formTextarea('terms', $_SESSION['form_special_request']['terms'], array('cols'=>30,'rows'=>3))?>
                </div>
            </div>
            
            <div class="field">
                <label for="want_date">Want it by</label>
                <div class="field_wrapper">
                    <? $want_date_field_value = $_SESSION['form_special_request']['want_date'] ? $_SESSION['form_special_request']['want_date'] : date('m/d/Y',time()+60*60*24*3) ?>
                    <?=$this->formText('want_date', $want_date_field_value, array("class"=>"small_tfield_date"))?>
                    
                </div>
            </div>
            
       </div>

        <br>
        <div class="join-button">
            <input type="submit" name="send" value="Send Request" class="green-button">
            <input type="hidden" name="send" value="Send Request" >
        </div>

    </form>
     

    <? 

        unset($_SESSION['form_special_request']) 
    ?>
</div>