<? $this->headTitle($this->page_title); ?>

<div class="row">
     <h2 class="title"><?=$this->user->username?>'s Profile</h2>


    <div class="col-lg-3 profile-left">
        <? echo $this->partial('partials/user-profile-left.phtml',array('user' => $this->user,'country' => $this->country,"active" => $this->profile_action)); ?>
    </div>

    <div class="col-lg-9">
<?

    switch($this->profile_action){
        case "profile":
            echo $this->partial('partials/user-profile-profile.phtml',$this);
        break;
        
        case "favorite":
            echo $this->partial('partials/user-profile-favorite.phtml',$this);
        break;
        
        case "following":
            echo $this->partial('partials/user-profile-following.phtml',$this);
        break;  
        
        case "friends":
            echo $this->partial('partials/user-profile-friends.phtml',$this);
        break; 
        
        case "edit":
            echo $this->partial('partials/user-profile-edit.phtml',$this);
        break; 
        
        case "special-requests":
            echo $this->partial('partials/user-profile-special-requests.phtml',$this);
        break;  
        
        case "videos":
            echo $this->partial('partials/user-profile-videos.phtml',$this);
        break; 
        
        case "chips":
            echo $this->partial('partials/user-profile-chips.phtml',$this);
        break;              
    }

?>      
    </div>
    <div class="clear"></div>
</div>

