<?
$page_title = "Banners ";

$this->headTitle($page_title);


?>
<div class="model_content">
    <?php
    echo $this->partial('partials/moderator-submenu.phtml',
        array("params" => $this->theme()->view->params,
            "type" => "model",
            "acl" => $this->acl,
            "user" => $this->model
        ));


    echo $this->partial("banner/banner-add-form.phtml", $this);
    ?>
</div>