<? $this->headTitle("Group Shows"); ?>

<div class="page-content round-corners" style="min-height: 300px; float: left;">

    <?= $this->notice ?>
    <div class="clear"></div>
    <h1 class="page-title">Group Shows</h1>

    <br>
    This page displays information on current Group Shows in progress as well as pending requests for Group Shows<br>
    Shows started by the members have notime limit when allmembers exit the show will automaticaly end or if performer
    ends it
    <br><br>

    <div class="clear"></div>

    <div class="group_show group_show_small">
        <div class="group_show_owner"><a href="javascript:;">Sherry</a></div>
        <img src="/uploads/photos/fb/ab/d6/07/ede95ff6c31252ed8ff3e9c7a6d22afd.jpg"/>
        <img src="/uploads/photos/fb/ab/d6/07/ede95ff6c31252ed8ff3e9c7a6d22afd.jpg"/>

        <div class="group_show_desc">

            <div class="group_show_topic group_show_topic_light">Show Topic: Having fun all day long!</div>
            <div class="group_show_info">
                <table cellpadding="1" cellspacing="1">
                    <tr>
                        <th>Status</th>
                        <th>Total</th>
                        <th>Collected</th>
                        <th>Time left</th>
                        <th>Created by</th>
                        <th>Duration</th>
                        <th>Camera handler</th>
                        <th>For</th>
                        <th>Members</th>
                    </tr>
                    <tr>
                        <td>Pending</td>
                        <td>100 chips</td>
                        <td>70 chips</td>
                        <td>4:39</td>
                        <td>Performer</td>
                        <td>5 min</td>
                        <td>no</td>
                        <td>Members only</td>
                        <td>#10</td>
                    </tr>
                </table>
            </div>
            <div class="group_show_button"><a href="javascript:;">Contribute</a></div>
        </div>
    </div>

    <div class="clear"></div>
    <h3 class="page_title"></h3>

    <div class="clear"></div>

    <div class="group_show group_show_small">
        <div class="group_show_owner"><a href="javascript:;">Honey</a></div>
        <img src="/uploads/photos/f7/8f/22/35/c57337c569b182b7f26098fab1bf6e75.jpg"/>
        <img src="/uploads/photos/f7/8f/22/35/c57337c569b182b7f26098fab1bf6e75.jpg"/>

        <div class="group_show_desc">

            <div class="group_show_topic">Topic: Bedroom stories!</div>
            <div class="group_show_info">
                <table cellpadding="1" cellspacing="1">
                    <tr>
                        <th>Status</th>
                        <th>Total</th>
                        <th>Collected</th>
                        <th>Time left</th>
                        <th>Created by</th>
                        <th>Duration</th>
                        <th>Camera handler</th>
                        <th>For</th>
                        <th>Members</th>
                    </tr>
                    <tr>
                        <td>Live</td>
                        <td></td>
                        <td></td>
                        <td>-:-:-</td>
                        <td>Member</td>
                        <td></td>
                        <td>no</td>
                        <td>Contributing Members only</td>
                        <td>#20</td>
                    </tr>
                </table>
            </div>
            <div class="group_show_button"><a href="javascript:;">Join</a></div>
        </div>
    </div>

    <div class="group_show group_show_small">
        <div class="group_show_owner"><a href="javascript:;">Tiffany</a></div>
        <img src="/uploads/photos/14/85/a5/27/8b00397ad890cd40e53ec4720f460412.jpg"/>
        <img src="/uploads/photos/14/85/a5/27/8b00397ad890cd40e53ec4720f460412.jpg"/>

        <div class="group_show_desc">

            <div class="group_show_topic">Topic: Strip time!</div>
            <div class="group_show_info">
                <table cellpadding="1" cellspacing="1">
                    <tr>
                        <th>Status</th>
                        <th>Total</th>
                        <th>Collected</th>
                        <th>Time left</th>
                        <th>Created by</th>
                        <th>Duration</th>
                        <th>Camera handler</th>
                        <th>For</th>
                        <th>Members</th>
                    </tr>
                    <tr>
                        <td>Live</td>
                        <td></td>
                        <td></td>
                        <td>-:-:-</td>
                        <td>Member</td>
                        <td></td>
                        <td>no</td>
                        <td>Members only</td>
                        <td>#30</td>
                    </tr>
                </table>
            </div>
            <div class="group_show_button"><a href="javascript:;">Show interest</a></div>
        </div>
    </div>

    <div class="clear"></div>

</div>
<div class="clear"></div>