<? $this->headTitle("Most Popular Room"); ?>

<div class="page-content round-corners" style="min-height: 300px; float: left;">

    <?= $this->notice ?>
    <h1 class="page-title">Most Popular Room</h1>

    <br>
    Here are the top 100 performers with the most active members in there chat. Performers with less activity are more
    likely to give you more personal attention. But you dont want to be the one that just missed what
    happened!!!<br><br>

    <div class="room room_small">
        <img src="/files/photos/fb/ab/d6/07/ede95ff6c31252ed8ff3e9c7a6d22afd.jpg"/>
        <img src="/files/photos/fb/ab/d6/07/ede95ff6c31252ed8ff3e9c7a6d22afd.jpg"/>

        <div class="room_desc">
            <div class="room_owner"><a href="javascript:;">Sherry</a></div>
            <div class="room_topic">Topic: Having fun all day long!</div>
            <div class="room_viewers">Current viewers: 10</div>
            <div class="room_visited">Visited: 30</div>
            <div class="room_popup"><a href="javascript:;">open pop up</a></div>
        </div>
    </div>

    <div class="room room_small">
        <img src="/files/photos/f7/8f/22/35/c57337c569b182b7f26098fab1bf6e75.jpg"/>
        <img src="/files/photos/f7/8f/22/35/c57337c569b182b7f26098fab1bf6e75.jpg"/>

        <div class="room_desc">
            <div class="room_owner"><a href="javascript:;">Honey</a></div>
            <div class="room_topic">Topic: Bedroom stories!</div>
            <div class="room_viewers">Current viewers: 15</div>
            <div class="room_visited">Visited: 35</div>
            <div class="room_popup"><a href="javascript:;">open pop up</a></div>
        </div>
    </div>

    <div class="room room_small">
        <img src="/files/photos/14/85/a5/27/8b00397ad890cd40e53ec4720f460412.jpg"/>
        <img src="/files/photos/14/85/a5/27/8b00397ad890cd40e53ec4720f460412.jpg"/>

        <div class="room_desc">
            <div class="room_owner"><a href="javascript:;">Tiffany</a></div>
            <div class="room_topic">Topic: Strip time!</div>
            <div class="room_viewers">Current viewers: 50</div>
            <div class="room_visited">Visited: 60</div>
            <div class="room_popup"><a href="javascript:;">open pop up</a></div>
        </div>
    </div>

    <div class="room room_small">
        <img src="/files/photos/fb/ab/d6/07/ede95ff6c31252ed8ff3e9c7a6d22afd.jpg"/>
        <img src="/files/photos/fb/ab/d6/07/ede95ff6c31252ed8ff3e9c7a6d22afd.jpg"/>

        <div class="room_desc">
            <div class="room_owner"><a href="javascript:;">Sherry</a></div>
            <div class="room_topic">Topic: Looking for men!</div>
            <div class="room_viewers">Current viewers: 20</div>
            <div class="room_visited">Visited: 100</div>
            <div class="room_popup"><a href="javascript:;">open pop up</a></div>
        </div>
    </div>

    <div class="clear"></div>

</div>
<div class="clear"></div>