<div class="my_twitter">
    <div class="widget-container">
        <?php
            echo $this->tw(
                [
                    'dataWidgetId' => '450962160126947329',
                        'href'         => 'https://twitter.com/anakaliyah',
                        'hrefText'     => 'My tweeter feed'
                    ],
                    true
                );
        ?>
    </div>
</div>
