<?= $this->partial('application/dashboard/partial/tab-menu'); ?>

<div class="row-fluid">
    <div class="span12">
        <h3>Change Password for <?php echo $this->zfcUserDisplayName() ?></h3>
        <?php if ($status === true) : ?>
            <div class="alert alert-success">Password changed successfully.</div>
        <?php elseif ($status === false) : ?>
            <div class="alert alert-error">Unable to update your password. Please try again.</div>
        <?php endif; ?>
        <?php

        $form = $this->changePasswordForm;

        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changepassword'));
        $form->setAttribute('method', 'post');

        $form->setAttribute('class', 'form-horizontal center');
        $form->get('submit')->setOptions(array('skipLabel' => true));
        $form->get('submit')->setAttributes(array("class" => "btn btn-magenta"));

        $emailElement = $form->get('identity');
        $emailElement->setValue($this->zfcUserIdentity()->getEmail());

        echo $this->ztbForm($form);
        ?>
    </div>
</div>