<div class="content col-sm-8">


    <!--<div style="width: 604px;height:143px;margin: 0 auto;background: #ea292a;"></div>-->
    <style>
        .player_box {
            width: 100%;
        }
    </style>

    <script src="/themes/anakaliyah/scripts/flowplayer-3.2.6.min.js"></script>


    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Bio</div>
                <div class="panel-body">
                    <span class="">  </span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">What Turns me on</div>

                <div class="panel-body">
                    <span>  </span>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">What Turns me off</div>
                <div class="panel-body">
                    <span>  </span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Things I do in private</div>
                <div class="panel-body">
                    <span>  </span>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Things I don't do in private</div>
                <div class="panel-body">
                    <span>  </span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Interests &amp; hobbies</div>
                <div class="panel-body">
                    <span>  </span>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">My Room rules</div>
                <div class="panel-body">
                    <span>  </span>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Top gifters</div>
                <div class="panel-body"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Top tippers</div>
                <div class="panel-body"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Reviews</div>
                <div class="panel-body">
                <span>
                    There are no reviews for <b>Charley Hegmann</b> yet.
                </span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Friends</div>
                <div class="panel-body">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Guestbook</div>
                <div class="panel-body">
                    <p class="rb-meta">
                        0&nbsp;
                        Messages</p>


                    <form action="/rbcomment/add" method="post" name="rbcomment" id="rbcomment"><input name="id"
                                                                                                       type="hidden"
                                                                                                       value=""><input
                            type="hidden" name="csrf"
                            value="ab07b034ca5aca766a08f2d7835d0603-4923455616e0c4b8920a3325bb8f8ca0"><input
                            name="thread" type="hidden" value="3599ce6448e2c85bc077fa1025443abba9844896"><input
                            name="uri" type="hidden" value="/guestbook/154">

                        <div class="rb-form-row">
                            You are not signed in. To be able to leave a message, please <a href="/account/login">
                                Sign In </a>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="clearfix"></div>
</div>